precision: 6

in_cap_search_params:
  low: 1.0e-17
  high: !!null
  step: 2.0e-15
  tol: 1.0e-16
  max_err: 1.0e-9
  overhead_factor: 20.0

out_cap_search_params:
  low: 1.0e-15
  high: !!null
  step: 40.0e-15
  tol: 1.0e-15
  max_err: 1.0e-9
  overhead_factor: 20.0

seq_search_params:
  tol: 20.0e-12
  max_margin: 2.0e-9
  overhead_factor: 2.0

seq_delay_thres: 0.05

tran_tbm_specs:
  sim_params:
    t_rst: 2.0e-9
    t_rst_rf: 100.0e-12
    t_clk_per: 40.0e-9
    t_clk_rf: 100.0e-12
    t_clk_delay: 20.0e-9
    t_bit: 20.0e-9
    t_rf: 100.0e-12

  rtol: 1.0e-8
  atol: 1.0e-22
  tran_options:
    maxstep: 2.0e-12
    errpreset: conservative

buf_params:
  export_pins: True
  inv_params:
    - {lch: 30, w_p: 110, w_n: 84, th_p: standard, th_n: standard, seg: 2}
    - {lch: 30, w_p: 110, w_n: 84, th_p: standard, th_n: standard, seg: 8}
